/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignedInRouteImport } from './routes/signed-in'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as GooglePickerRouteImport } from './routes/google-picker'
import { Route as IndexRouteImport } from './routes/index'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignedInRoute = SignedInRouteImport.update({
  id: '/signed-in',
  path: '/signed-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const GooglePickerRoute = GooglePickerRouteImport.update({
  id: '/google-picker',
  path: '/google-picker',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/google-picker': typeof GooglePickerRoute
  '/privacy': typeof PrivacyRoute
  '/signed-in': typeof SignedInRoute
  '/signin': typeof SigninRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/google-picker': typeof GooglePickerRoute
  '/privacy': typeof PrivacyRoute
  '/signed-in': typeof SignedInRoute
  '/signin': typeof SigninRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/google-picker': typeof GooglePickerRoute
  '/privacy': typeof PrivacyRoute
  '/signed-in': typeof SignedInRoute
  '/signin': typeof SigninRoute
  '/terms': typeof TermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/google-picker'
    | '/privacy'
    | '/signed-in'
    | '/signin'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/google-picker' | '/privacy' | '/signed-in' | '/signin' | '/terms'
  id:
    | '__root__'
    | '/'
    | '/google-picker'
    | '/privacy'
    | '/signed-in'
    | '/signin'
    | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GooglePickerRoute: typeof GooglePickerRoute
  PrivacyRoute: typeof PrivacyRoute
  SignedInRoute: typeof SignedInRoute
  SigninRoute: typeof SigninRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signed-in': {
      id: '/signed-in'
      path: '/signed-in'
      fullPath: '/signed-in'
      preLoaderRoute: typeof SignedInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google-picker': {
      id: '/google-picker'
      path: '/google-picker'
      fullPath: '/google-picker'
      preLoaderRoute: typeof GooglePickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GooglePickerRoute: GooglePickerRoute,
  PrivacyRoute: PrivacyRoute,
  SignedInRoute: SignedInRoute,
  SigninRoute: SigninRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
